name: Build and Deploy
on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1

concurrency:
  group: deploy-site
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js current
        uses: actions/setup-node@v4
        with:
          node-version: current

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # publish_dir is the folder where build.js outputs the site
          publish_dir: dist
          # publish_branch is the branch in the repository for GitHub Pages
          publish_branch: gh-pages

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          neocities_supporter: false
          preview_before_deploy: true
          dist_dir: dist
