name: Build Site
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js current
        uses: actions/setup-node@v4
        with:
          node-version: current

      - name: Install dependencies & build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # publish_dir is the folder where build.js outputs the site
          publish_dir: dist
          # publish_branch is the branch in the repository for GitHub Pages
          publish_branch: gh-pages
